ATM-Consulting/dolibarr_module_operationorder

class/actions_operationorder.class.php, core/modules/modOperationOrder.class.php, core/triggers/interface_99_modOperationOrder_OperationOrdertrigger.class.php, langs/fr_FR/operationorder.lang, operationorder_card.php
Tâche : Il doit être possible de passer une commande fournisseur depuis un OR. Cette commande fournisseur est lié à l’OR
Concrètement cela ajoute un élément/element lors de la création d'une commande fourn depuis un ordre de réparation.
=> T1779 - add button to create supplier order

class/operationorder.class.php, langs/fr_FR/operationorder.lang, list.php
J'ajoute la colonne de dépassement sur la liste avec filtre et tri
Pour bien fonctionner il y a besoin de valider une PR abricot https://github.com/ATM-Consulting/dolibarr_module_abricot/pull/102
=> T1769 - Add overshot column

list.php
Ajoute dynamiquement les extrafields à une liste type listeview des Ordre de réparation
=> Fix missing extrafields in list

class/operationorder.class.php, core/modules/operationorder/doc/pdf_olaf.modules.php, langs/fr_FR/operationorder.lang, list.php, operationorder_card.php
Un premier jet du PDF standard
=> T1780 pdf ordre de réparation

list.php
Ajout du hook "printFieldListJoin" pour enrichir la requête sql de la liste des or.
=> New t1771 add hook print field list join

class/operationorder.class.php
Dans ce cas précis le trigger n'était pas approprié.
=> ADD hook - T2134

operationorder_planning.php
Le resize était désactivé, en l'activant j'ai remarqué que la tooltip ne disparaissait plus après un resize
=> FIX resize and tooltip not hiding

class/operationorder.class.php, scripts/interface.php
Lié à la PR https://gogs.atm-consulting.fr/ATM-Consulting/doli-cli-theobald/pulls/32
=> Standard Date Planned Field Operation Order

operationorder_planning.php
Initiation d'un Hook + réorganisation des eventSources de fullcalendar pour pouvoir les modifier
=> T1790 - Init Hook + Variable "eventSources_parameters"

admin/operationorder_setup.php, class/actions_operationorder.class.php, class/operationorder.class.php, class/operationorderstatus.class.php, core/modules/modOperationOrder.class.php, langs/fr_FR/operationorder.lang, operationorder_card.php, operationorderstatus_card.php, scripts/interface.php
=> T1785 stock alert

admin/operationorder_setup.php, class/actions_operationorder.class.php, class/operationorderuserplanning.class.php, core/modules/modOperationOrder.class.php, langs/fr_FR/operationorder.lang, lib/operationorder.lib.php, operationorder_planning.php, operationorder_userplanning.php, script/create-maj-base.php
Planning d'horaires par utilisateur et groupe d'utilisateurs avec permissions. 
Liée à la PR d'abricot : https://github.com/ATM-Consulting/dolibarr_module_abricot/pull/108
=> New t1801 saisie horaires hebdomadaires

class/operationordertasktime.class.php, script/create-maj-base.php
Ajout de l'objet "OperationOrderTaskTime"
=> Add table "llx_operationordertasktime"

langs/en_US/operationorder.lang
=> update - add setup

class/operationorder.class.php
add flat parameters to allow getting array with childs with only one dimension
=> add flat array for nested lines

class/operationorder.class.php, operationorder_planning.php, scripts/interface.php
depends on PR https://github.com/ATM-Consulting/dolibarr_module_operationorder/pull/37
Add a progress bar on events in operationorder_planning
=> add progressbar

class/operationorder.class.php, lib/operationorder.lib.php, operationorder_card.php
quand on modifie la quantité ça met à jour les temps
=> Fix update time when updating qty

admin/operationorderstatus_extrafields.php, class/operationorder.class.php, class/operationorderstatus.class.php, langs/fr_FR/operationorder.lang, lib/operationorder.lib.php
Ajout de la gestion d'extrafields sur les statuts
PR à merger avec celle de clitheobald (PR 45)
=> New cron on km

class/operationorder.class.php
Si je modifie la quantité d'une ligne de niveau 1, je doit impacter les quantité de lignes inférieur (et donc le temps)
=> NEW update recursively childs when updating parent

class/operationorder.class.php, class/operationorderhistory.class.php
Gestion de l'historisation du cas particulier des status + on retire l'évènement créé en automatique car il n'a plus lieu d'etre
=> FIX history status

class/operationorder.class.php, core/modules/modOperationOrder.class.php, langs/fr_FR/operationorder.lang, operationorder_card.php
Cout total HT remboursement : Somme du total HT de toutes les lignes de niveau 1 de l'OR qui sont des services qui sont "Ventilation produit"
Cout Total HT MO : Somme du total HT de toutes les lignes de niveau 1 de l'OR qui sont des service qui sont "pointable OR" (attribut complémentaire service)
Cout Total HT Extérieur: Somme du total HT de toutes les lignes de l'OR qui sont des services qui sont "Ordre de réparation : ouvre une creation de commande founisseur" (attribut complémentaire service)
Cout Total HT Piéce : Somme du total HT de toutes les lignes de l'OR qui sont des produits
Cout Total HT : Somme de ces quatre Totaux
=> T1802 - NEW calcul totaux

js/manager.js.php, scripts/managerinterface.php
Création variable $data['courantOR'] contenant ref de l'OR courant
Affichage de la variable dans le champ "OR courant"
=> Affichage ref OR dans champ "OR courant"

scripts/interface.php
Changement d'un arrondi "floor()" en arrondi "round()"
=> FIX : correction arrondis temps des produits sur OR

class/operationorder.class.php
2eme Retour : 
Remplacement d'un arrondis floor par un arrondis round dans la fonction recurciveAddChildLines()
=> FIX : arrondis temps OR 2

list.php
Prise en compte des filtres pour les marques-pages (renvoie vers une liste filtrée, et pas vers une liste complète sans filtre)
=> FIX : marque page avec filtre sur liste OR (ne fonctionnait pas) 

core/modules/modOperationOrder.class.php, langs/fr_FR/operationorder.lang, lib/operationorder.lib.php, operationorder_orplanning.php, scripts/interface.php
Ajoute la possibilité d'éditer/supprimer un temps saisi via l'écran atelier ou le planning d'activités journalière.
- modification d'une saisie limité par la plage libre dans le planning
- gestion d'erreurs sur la modification
- nouveau droit "supprimer une saisie"
- nouveau droit "modification des saisie"
- suppression d'une saisie soumise à ce droit en front et back 
- modification du temps passé sur les lignes d'OR liées en fonction de l'action
=> T1782 add edit counters

admin/operationorder_setup.php, css/dailySchedule.css.php, langs/fr_FR/operationorder.lang, lib/operationorder.lib.php
Afficher les OR qui sont en cours d'exécution
=> Fix activites journalieres or en cours

list.php
**Modification de la listView :**
- Ajout de l'attribut "table" = "t" dans la partie "search" du listViewConfig pour la date de planification ('planned_date') et la date de creation ('date_creation')
- Ajout du champ 'planned_date' à la partie "type" du listViewConfig tel que : 'planned_date' => 'date'
=> FIX : filtres dates listeOR 

class/operationorder.class.php, langs/fr_FR/operationorder.lang, operationorder_card.php
Lors de l'édition d'une ligne d'OR, lorsque le prix est inférieur au prix minimum du produit, le prix prend pour valeur le prix minimum et un message warning s'affiche
=> TK12014 - Edit Line : price < price min

class/operationorder.class.php
- FIX : Use QtyUser to calcul total ht or lines. To calculate total HT of an OR line, use quantity used instead of expected quantity
=> FIX TK12072 - Use QtyUser to calcul total ht or lines

class/operationorder.class.php, operationorder_card.php
Ajout de la possibilité pour un admin de saisir un prix de piece
inferieur au prix mini.
=> Ajout de la possibilité pour un admin de saisir un prix de piece

class/operationorder.class.php, operationorder_card.php
Correction d'un BUG d'affichage sur les quantité débitée dans les OR, si la quantité est négative, le signe - n'apparait pas et rien n'averti l'utilisateur de la quantité négative
=> Correction d'un BUG d'affichage

operationorder_card.php
Modification des droits de modification de status des OR
=> Modification des droits
